honor timeouts defined in the action
StackStorm-Exchange/stackstorm-foreman pull request #15
Opened 2022-09-01 13:36 UTC by cyberkov

Hello!

As of now, the underlying Foreman library is using a timeout of 60 seconds ( https://python-foreman.readthedocs.io/en/latest/client/ ) which is not configurable in the given action.
Some actions are unfortunately long-running and I have to set this value.

Cheers
Hannes

2022-09-07 12:13 UTC, armab requested changes
Thanks for the contribution! The change looks good.

As usual, we'll need a Changelog record and bumping the pack version in pack.yaml.
This way automation will take care of creating a new release for this pack for StackStorm-Exchange.

2023-01-30 17:30 UTC, cyberkov commented
Sorry I pushed too much. I'll fix it.

2023-01-31 13:27 UTC, arm4b reviewed
Looks like some tests need an update 
https://github.com/StackStorm-Exchange/stackstorm-foreman/actions/runs/4046542435/jobs/6976061335#step:6:1168 

Besides that, looks good

2023-01-31 15:22 UTC, cyberkov commented
Hello!

I think it's working now :)
Thank you for your time and effort!

Cheers Hannes

2023-02-01 12:43 UTC, arm4b approved these changes
Thanks for the contribution!

2023-02-01 12:44 UTC, merged